# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtiLwCli < Formula
  desc "CLI of The Things Stack Enterprise for LoRaWAN"
  homepage "https://www.thethingsindustries.com"
  version "3.13.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.13.2/lorawan-stack-cli_3.13.2_darwin_amd64.tar.gz"
    sha256 "8978753c4f6d820572023395987f50779d950c3b73fa18411f58e65de45d7b16"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.13.2/lorawan-stack-cli_3.13.2_darwin_arm64.tar.gz"
    sha256 "3bcab88d77603dcf482427fd5ff839b793674decabff0debd64e0600392ff636"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.13.2/lorawan-stack-cli_3.13.2_linux_amd64.tar.gz"
    sha256 "56d271ac81610fad1c982fc19b416e0d979c04b331631e435b3064872a665f8e"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.13.2/lorawan-stack-cli_3.13.2_linux_armv6.tar.gz"
    sha256 "30267caf4349a71febb83baf6c2aede4d3b67ae3c09ee100d2d41b71b78c214e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.13.2/lorawan-stack-cli_3.13.2_linux_arm64.tar.gz"
    sha256 "04bbcd939a76698fcdbbd77ffb5b3021999a1b093b4b282b8fa6022c21b164ab"
  end

  conflicts_with "tti-lw-stack"

  def install
    bin.install "tti-lw-cli"
    bash_completion.install "config/completion/bash/tti-lw-cli"
    zsh_completion.install "config/completion/zsh/_tti-lw-cli"
    fish_completion.install "config/completion/fish/tti-lw-cli.fish"
  end
end
