# This file was generated by GoReleaser. DO NOT EDIT.
class TtiLwCli < Formula
  desc "CLI of The Things Stack for LoRaWAN"
  homepage "https://www.thethingsindustries.com"
  version "3.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.2.1/lorawan-stack-cli_3.2.1_darwin_amd64.tar.gz"
    sha256 "e143ca63d681892d6ee2e832567f1394c95313fc31e9a2a001b658e0744e81e6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.2.1/lorawan-stack-cli_3.2.1_linux_amd64.tar.gz"
      sha256 "09ce9832aed7c04fbae99d9976cce6ee64bdc03ed3ee5c4be18c8153e7cc7688"
    end
  end
  
  conflicts_with "tti-lw-stack"

  def install
    bin.install "tti-lw-cli"
    libexec.install doc
  end
end
