# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtiLwStack < Formula
  desc "The Things Stack Enterprise for LoRaWAN"
  homepage "https://www.thethingsindustries.com"
  version "3.14.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.14.1/lorawan-stack_3.14.1_darwin_amd64.tar.gz"
    sha256 "4064ee5e1ef96ca28f034269fd26cdc776568b08d36e4b9f2439eb77f88dca8a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.14.1/lorawan-stack_3.14.1_darwin_arm64.tar.gz"
    sha256 "7a2afafa21eaa53159bd4db43d159ace1add0f46e0a0f29c71fcc8da66d61d6e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.14.1/lorawan-stack_3.14.1_linux_amd64.tar.gz"
    sha256 "c00427993ac466b7180b5d0e90c45c3eb959490c05f634784a5fc8b69b5724a1"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.14.1/lorawan-stack_3.14.1_linux_armv6.tar.gz"
    sha256 "3c5daa0f397286d258410fe172cc352f34d50384bbd976e98e2c7eba0c9e2349"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://the-things-enterprise-stack-releases.s3-eu-west-1.amazonaws.com/3.14.1/lorawan-stack_3.14.1_linux_arm64.tar.gz"
    sha256 "a8481d0b052500f898972fac3c62143039ecd387fab07bec5a0fe4b93e7695b8"
  end

  conflicts_with "tti-lw-cli"

  def install
    bin.install "tti-lw-cli"
    libexec.install %w[tti-lw-stack public]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"tti-lw-stack").write_env_script libexec/"tti-lw-stack", env
    bash_completion.install "config/completion/bash/tti-lw-cli"
    zsh_completion.install "config/completion/zsh/_tti-lw-cli"
    fish_completion.install "config/completion/fish/tti-lw-cli.fish"
    bash_completion.install "config/completion/bash/tti-lw-stack"
    zsh_completion.install "config/completion/zsh/_tti-lw-stack"
    fish_completion.install "config/completion/fish/tti-lw-stack.fish"
  end
end
