# This file was generated by GoReleaser. DO NOT EDIT.
class TtiLwCli < Formula
  desc "CLI of The Things Stack for LoRaWAN"
  homepage "https://www.thethingsindustries.com"
  version "3.9.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.9.3/lorawan-stack-cli_3.9.3_darwin_amd64.tar.gz"
    sha256 "99164d916f0f68359cbd1cec6340c8e809736c22e86a253838e63d85c7379c3b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.9.3/lorawan-stack-cli_3.9.3_linux_amd64.tar.gz"
      sha256 "3d008a5ee0d2fd91bd859722721df2b411bc5d47eb7084e190d92353910e902f"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.9.3/lorawan-stack-cli_3.9.3_linux_arm64.tar.gz"
        sha256 "9bb9e7e0de7b52144f8cc99587662eb097f487283a43220041eae80cd3802e00"
      else
        url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.9.3/lorawan-stack-cli_3.9.3_linux_armv6.tar.gz"
        sha256 "1840fd1853b2f4df7314387fb55beaf893987e8181f495f9327fa5fcc2b9325f"
      end
    end
  end
  
  conflicts_with "tti-lw-stack"

  def install
    bin.install "tti-lw-cli"
    bash_completion.install "config/completion/bash/tti-lw-cli"
    zsh_completion.install "config/completion/zsh/_tti-lw-cli"
    fish_completion.install "config/completion/fish/tti-lw-cli.fish"
  end
end
