# This file was generated by GoReleaser. DO NOT EDIT.
class TtiLwStack < Formula
  desc "The Things Stack for LoRaWAN"
  homepage "https://www.thethingsindustries.com"
  version "3.10.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.9/lorawan-stack_3.10.9_darwin_amd64.tar.gz"
    sha256 "e529ba7d3bf2697f849dcf9acc642247f580c83fa980f2a5dffc8d6367c032f2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.9/lorawan-stack_3.10.9_linux_amd64.tar.gz"
      sha256 "3f1afc472ba0e1bf81385400d3a80c9c408cc72d05e88a70396311bdcf5fe6ec"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.9/lorawan-stack_3.10.9_linux_arm64.tar.gz"
        sha256 "bf10f8c6039acc8b7195475b85f788413497c811ea3af81d92eb6cdf252eb541"
      else
        url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.9/lorawan-stack_3.10.9_linux_armv6.tar.gz"
        sha256 "e87b1925ea2b863843a41c46ed42734777389419d58112e2e50ebd1904c31a86"
      end
    end
  end
  
  conflicts_with "tti-lw-cli"

  def install
    bin.install "tti-lw-cli"
    libexec.install %w[tti-lw-stack public]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"tti-lw-stack").write_env_script libexec/"tti-lw-stack", env
    bash_completion.install "config/completion/bash/tti-lw-cli"
    zsh_completion.install "config/completion/zsh/_tti-lw-cli"
    fish_completion.install "config/completion/fish/tti-lw-cli.fish"
    bash_completion.install "config/completion/bash/tti-lw-stack"
    zsh_completion.install "config/completion/zsh/_tti-lw-stack"
    fish_completion.install "config/completion/fish/tti-lw-stack.fish"
  end
end
