# This file was generated by GoReleaser. DO NOT EDIT.
class TtiLwStack < Formula
  desc "The Things Stack for LoRaWAN"
  homepage "https://www.thethingsindustries.com"
  version "3.10.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_darwin_amd64.tar.gz"
    sha256 "75f6dad27625d19fd26f9f78fe743380f92ab5178570a40dc85009858871d840"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_linux_amd64.tar.gz"
      sha256 "cb1d4f049ff71f22be86e3617ad725c81b3e894877f5400f6d001921247c364d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_linux_arm64.tar.gz"
        sha256 "539e0e16b851303509e54ef9e0ae361aa8014b3ea906913c380ee68dededd0c1"
      else
        url "https://github.com/TheThingsIndustries/lorawan-stack/releases/download/v3.10.7/lorawan-stack_3.10.7_linux_armv6.tar.gz"
        sha256 "bcb4bf5a5d2781f32dad54370cd027d4e759f9b2a3d6d0fd1f7b2c97919734f4"
      end
    end
  end
  
  conflicts_with "tti-lw-cli"

  def install
    bin.install "tti-lw-cli"
    libexec.install %w[tti-lw-stack public]
    env = {
        :TTN_LW_HTTP_STATIC_SEARCH_PATH => libexec/"public"
    }
    (bin/"tti-lw-stack").write_env_script libexec/"tti-lw-stack", env
    bash_completion.install "config/completion/bash/tti-lw-cli"
    zsh_completion.install "config/completion/zsh/_tti-lw-cli"
    fish_completion.install "config/completion/fish/tti-lw-cli.fish"
    bash_completion.install "config/completion/bash/tti-lw-stack"
    zsh_completion.install "config/completion/zsh/_tti-lw-stack"
    fish_completion.install "config/completion/fish/tti-lw-stack.fish"
  end
end
